version: '3.3'
services:
  rabbitmq:
    build:
      context: .
      dockerfile: docker/rabbitmq/Dockerfile
    restart: always
    ports:
      - 5672
      - 15672
    hostname: rabbitmq
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/ravens
      - ~/.composer/:/root/.composer
      - ${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}
    environment:
      - SSH_AUTH_SOCK=${SSH_AUTH_SOCK}
    depends_on:
      - rabbitmq
